---

- debug:
    msg: "imported RedHat/generic/assert-systemd-tmpfiles.yml"

- name: Check if file /etc/tmpfiles.d/sap.conf exists
  shell: test -f /etc/tmpfiles.d/sap.conf
  register: sap_conf_result
  ignore_errors: yes
  changed_when: no

- name: Assert that file /etc/tmpfiles.d/sap.conf exists
  assert:
    that:
      - sap_conf_result.rc == 0
    fail_msg: "FAIL: File '/etc/tmpfiles.d/sap.conf' does not exist!"
    success_msg: "PASS: File '/etc/tmpfiles.d/sap.conf' exists."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
